import { Component, Vue } from 'vue-property-decorator'
import TermAndCondition from "./tnc.vue"
import { DialogUtils, LanguageUtils, ValidateUtils } from "@/utils";
// LanguageUtils.lang("https://www.centralpattana.co.th/th/sustainability/corporate-governance/privacy-policy", "https://www.centralpattana.co.th/en/sustainability/corporate-governance/privacy-policy")
@Component({
    // components: { ContactComponent }
})
export default class ContactsComponent extends Vue {

    private get text() {
        return {
            url: LanguageUtils.lang("https://www.centralpattana.co.th/th/sustainability/corporate-governance/privacy-policy", "https://www.centralpattana.co.th/en/sustainability/corporate-governance/privacy-policy"),
            urlcookie: LanguageUtils.lang("https://www.centralpattana.co.th/th/sustainability/corporate-governance/cookie-policy", "https://www.centralpattana.co.th/en/sustainability/corporate-governance/cookie-policy"),
            maincontent: LanguageUtils.lang(`บริษัท เซ็นทรัลพัฒนา จำกัด (มหาชน) (ต่อไปนี้เรียกว่า “บริษัท”)
            ยินดีต้อนรับท่านเข้าสู่บริการต่างๆ ในเว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media) ของบริษัท บริการข่าวสาร ข้อมูลต่างๆ
            และบริการอื่นๆ แก่ผู้รับบริการ (ต่อไปนี้จะรวมเรียกว่า “บริการ”)
            ในการใช้บริการเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social
            Media) ของท่านจะอยู่ภายใต้ข้อกำหนดและเงื่อนไขฉบับนี้ ดังนั้น
            ขอความกรุณาท่านศึกษาข้อกำหนดและเงื่อนไขฉบับนี้โดยละเอียดก่อนการเข้าใช้บริการ
            บริการของบริษัทมีความหลากหลาย
            ในบางครั้งจึงอาจมีเงื่อนไขหรือข้อกำหนดเพิ่มเติมเฉพาะในส่วนของบริการนั้นๆ
            โดยบริษัทจะแจ้งข้อกำหนดเพิ่มเติมไปกับบริการที่เกี่ยวข้อง
            และข้อกำหนดเพิ่มเติมเหล่านั้นถือว่าเป็นส่วนหนึ่งของข้อตกลงระหว่างท่านกับบริษัทหากท่านใช้บริการนั้น`, `We, Central Pattana Public Company limited (hereinafter referred to as the “Company”) welcome the service users (hereinafter referred to as “you”) to the services on this website, mobile application and social media of the Company, which provides you news, information and other services (hereinafter referred to as the “services”). By logging into the system, you agree to comply with the terms and conditions of use (“Terms and Conditions of Use”) hereinafter set forth, therefore, please read the Terms and Conditions of Use thoroughly prior to accessing the services. Regarding to various services, there may be additional terms and conditions specific to the service. The Company will inform you about the additional terms and conditions of the service and such additional terms and conditions shall form part of the agreement between you and the Company of such service used.`),
            maincontent1: LanguageUtils.lang(`ทั้งนี้ ในการใช้บริการ โปรดกดปุ่ม “ตกลง” หลังจากท่านกดปุ่มตกลง
            “ให้ถือว่าท่านได้ตกลงที่จะปฏิบัติตามข้อกำหนดและเงื่อนไขการให้บริการที่กำหนดไว้นี้”
            หากท่านผู้ใช้บริการไม่ประสงค์ที่จะผูกพันตามข้อกำหนดและเงื่อนไขการให้บริการ
            ขอความกรุณาท่านยุติการเข้าชมและใช้งานเว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media) นี้ในทันที`, `If you select “I agree” button, it shall be deemed that you agree to comply with the Terms and Conditions of Use hereof. In case you do not wish to comply with the Terms and Conditions of Use, please kindly exit and do not use our website, mobile application and social media.`),
            TermsofService: LanguageUtils.lang(`เงื่อนไขการให้บริการ`, `Term of Service`),
            TermsofService1: LanguageUtils.lang(`บริษัทจัดให้มีเว็บไซต์และ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ขึ้นเพื่ออำนวยความสะดวกในการให้บริการแก่ผู้รับบริการ ซึ่งข้อมูลที่แสดงไว้เป็นข้อมูลเพื่อประโยชน์ในการประกอบการพิจารณาการใช้บริการของผู้รับบริการ บริษัทขอสงวนสิทธิในการระงับการเผยแพร่ เปลี่ยนแปลง แก้ไข ยกเลิกหรือปรับปรุงข้อมูลเมื่อใดก็ได้ โดยไม่จำเป็นต้องแจ้งให้ทราบล่วงหน้า`, `The Company creates this website, mobile application and social media in order to facilitate you. The information provided herein is for your consideration in using the services of the Company, therefore, we shall reserve the right to publish, modify, edit, disregard or update the information without prior notice.`),
            TermsofService2: LanguageUtils.lang(`อย่างไรก็ดี การเปลี่ยนแปลงใด ๆ ที่เกี่ยวกับข้อตกลงและเงื่อนไขการใช้จะมีการเผยแพร่ไว้ในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของบริษัทและเมื่อท่านได้เข้าใช้เว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ภายหลังการเปลี่ยนแปลงดังกล่าวแล้ว ย่อมถือว่าท่านตกลงยอมรับข้อตกลงและเงื่อนไขการใช้ทั้งหมดตามที่ได้เปลี่ยนแปลงแล้ว ดังนั้น ท่านจึงควรติดตามข้อตกลงและเงื่อนไขการใช้งานเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ที่กำหนดไว้นี้อยู่เสมอ`, `Any change to the Terms and Conditions of Use shall be posted in this website, mobile application and social media. When you access to this website, mobile application and social media after such change has been made, it shall be deemed that you accept and agree with such Terms and Conditions of Use. Hence, you are responsible for regularly check the Terms and Conditions of Use.`),
            OwnershipandIntellectualProperty: LanguageUtils.lang(`สิทธิในทรัพย์สินทางปัญญา`, `Ownership and Intellectual Property`),
            OwnershipandIntellectualProperty1: LanguageUtils.lang(`บริษัทเป็นเจ้าของลิขสิทธิ์ หรือสิทธิในทรัพย์สินทางปัญญาในเนื้อหาต่างๆ ที่แสดงบนเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ ซึ่งครอบคลุมถึงข้อความ บทความ รูปภาพ วีดิทัศน์ เสียง กราฟฟิค หรือโปรแกรมคอมพิวเตอร์ ข้อมูลใดๆ โปรแกรมใดๆ ตลอดจนซอฟท์แวร์ที่ใช้ในเว็บไซต์และ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ (รวมเรียกว่า “เนื้อหา”) เว้นแต่จะระบุไว้เป็นอย่างอื่นโดยชัดแจ้ง เนื้อหาใดๆ ในเว็บไซต์และ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้อยู่ภายใต้ความคุ้มครองของกฎหมายทรัพย์สินทางปัญญา และ/หรือกรรมสิทธิ์ตามกฎหมายไทย ตลอดจนกฎหมายต่างประเทศที่เกี่ยวข้อง`, `Copy rights or any intellectual property rights of the contents on this website, mobile application and social media, including any materials contained in this website, mobile application and social media, including but not limited to, messages, contents, pictures, photos, video, audios, graphics, computer program, graphics, audios, any form of information, any programs, software include in or made available on or through this website, mobile application and social media (collectively referred to as “Content” or “Contents”) are owned by Company, unless expressly stipulated otherwise. All of the Contents are protected by intellectual property and/or other forms of propriety rights under the laws of Thailand and/or other countries.`),
            OwnershipandIntellectualProperty2: LanguageUtils.lang(`เว้นแต่มีข้อความระบุไว้เป็นอย่างอื่นในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ บรรดาเนื้อหา ไฟล์ หรือเอกสารที่ปรากฏในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ ท่านมีสิทธิเพียงเข้าดู ดาวน์โหลด อัพโหลดเนื้อหา และพิมพ์เนื้อหาดังกล่าว เฉพาะเพื่อประโยชน์แก่การใช้งานในทางส่วนตัวและต้องไม่ใช่การใช้งานที่เป็นไปเพื่อประโยชน์ในทางการค้า และท่านตกลงที่จะเก็บบรรดาข้อความซึ่งเกี่ยวกับการแสดงถึงลิขสิทธิ์และสิทธิในความเป็นเจ้าของอื่นใดที่ปรากฏในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ไว้ด้วย ทั้งนี้ ท่านต้องไม่ทำสำเนา หรือจัดเก็บ หรือดาวน์โหลดเนื้อหาไม่ว่าจะในรูปของเอกสารหรือในรูปแบบสื่ออิเล็กทรอนิกส์อื่นใดอันมีวัตถุประสงค์เพื่อการส่ง โอน จัดทำ เผยแพร่ พิมพ์ ทำซ้ำ ดัดแปลง สร้างงานที่พัฒนา นำออกแสดง แพร่กระจาย จำหน่าย ให้สิทธิ เช่า ให้เช่า หรือโอนเนื้อหาใด ๆ ให้แก่บุคคลภายนอก ไม่ว่าการกระทำดังกล่าวจะเป็นไปเพื่อประโยชน์ในทางการค้าหรือได้รับประโยชน์เป็นสิ่งตอบแทนอื่นใดหรือไม่ก็ตาม เว้นแต่จะได้รับความยินยอมเป็นลายลักษณ์อักษรล่วงหน้าจากบริษัทก่อนดำเนินการ`, `Unless otherwise indicated in this website, mobile application and social media, any Contents, files or documents provided on this website, mobile application and social media, you may only view, download, upload the Contents and print any document of the Contents for your own personal and non-commercial use. On this basis, you also agree to keep all contents pertaining to copyright and other right of ownership that appear in this website, mobile application and social media. You may not copy, store or download either in hard copy, copy in electronics format or in any other forms for the purpose in transmit, transfer, perform, broadcast, publish, reproduce, create a derivative work from, display, distribute, sell, license, rent, lease or otherwise transfer any of Contents to any third person whether for direct commercial or any gain or otherwise without the prior written permission from the Company.`),
            DisclaimerandLimitationofLiability: LanguageUtils.lang(`ข้อสงวนสิทธิ์และข้อจำกัดความรับผิด`, `Disclaimer and Limitation of Liability`),
            DisclaimerandLimitationofLiability1: LanguageUtils.lang(`ข้อมูลที่แสดงในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้เป็นข้อมูลที่ได้นำเสนอตามสภาพที่ได้รับจากแหล่งที่น่าจะเชื่อถือได้ แต่บริษัทไม่อาจรับรองว่าข้อมูลนั้นถูกต้องหรือสมบูรณ์เพื่อการใช้ในทางการค้าหรือประโยชน์อื่นใด ผู้ใช้บริการพึงใช้วิจารณญาณด้วยตนเอง โดยบริษัทจะไม่รับผิดชอบในความเสียหาย หรือความสูญหายใด ๆ ที่เกิดจากการใช้เว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) หรือเนื้อหาใดๆ ในทุกกรณี`, `The Contents contained in this website, mobile application and social media are presented based on “as is” basis without direct or indirect guarantees or warranties by the Company of any kind. In no event shall the Company be responsible for any loss or damage or any profit and loss arising from the use of this website, mobile application and social media and/or the use of Contents contained herein in any circumstance.`),
            DisclaimerandLimitationofLiability2: LanguageUtils.lang(`บริษัทไม่รับรองว่าการเข้าถึง และการใช้เว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้จะเป็นไปอย่างต่อเนื่อง ไม่หยุดชะงัก หรือปราศจากความล่าช้า หรือข้อผิดพลาด บริษัทไม่รับรองว่าเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ปราศจากซอฟต์แวร์ที่มีจุดประสงค์มุ่งร้ายต่อระบบ หรือข้อมูลในระบบของท่าน อาทิ ไวรัส หรือไฟล์ซึ่งเป็นอันตรายอื่น ๆ (รวมเรียกว่า “ความบกพร่อง”) ทั้งนี้ ไม่ว่าความบกพร่องดังกล่าวจะเกิดขึ้นจากบุคคล หรือความขัดข้องทางเทคนิค หรือเหตุสุดวิสัยอย่างอื่น โดยบริษัทไม่รับผิดชอบในความเสียหาย หรือความสูญหายใด ๆ ที่เกิดจากความบกพร่องเหล่านั้นในทุกกรณี`, `The Company does not warrant that the access and use of this website, mobile application and social media shall be continued, uninterrupted or without delays or any errors. Moreover, the Company does not warrant that website, mobile application and social media shall be free of malicious programs which may cause damage to system or information in your system, for instance, viruses, or other harmful files (collectively referred to as “Defects”) regardless of whether such Defects are caused by human or electronic error or other events beyond its control. The Company shall not be responsible for any damage or loss arising from such Defects in any circumstances.`),
            DisclaimerandLimitationofLiability3: LanguageUtils.lang(`บริษัทสงวนสิทธิ์ในการพิจารณาไม่อนุญาตให้ท่านใช้บริการเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ รวมถึงสงวนสิทธิ์ในการเปลี่ยนแปลง หรือระงับการให้บริการเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของบริษัท ไม่ว่าบางส่วนหรือทั้งหมดและไม่ว่าในเวลาใด ๆ แก่ท่าน โดยไม่จำเป็นต้องบอกกล่าวหรือระบุเหตุผลในการดำเนินการนั้น`, `The Company reserves its rights not to grant you permission to use this website, mobile application and social media and may change or withdraw this website, mobile application and social media, in part or in whole, at any time without any prior notice or state of purposes in doing so.`),
            DisclaimerandLimitationofLiability4: LanguageUtils.lang(`นอกเหนือจากที่กำหนดไว้ในข้อตกลงและเงื่อนไขการใช้นี้ บริษัท กรรมการ ผู้จัดการ ผู้บริหาร พนักงาน ลูกจ้าง ตัวแทน หรือที่ปรึกษาของบริษัท จะไม่รับผิดในความผิดพลาดใด ๆ ของเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของบริษัท หรือจากข้อมูล เนื้อหาที่ปรากฏในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของบริษัทตลอดจนไม่รับผิดในผลของการละเว้นการกระทำใด ๆ ที่เกี่ยวข้องกับเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ ไม่ว่าจะเกิดจากสัญญา ละเมิด ประมาท หรือเหตุอื่นใดที่อาจจะเกิดขึ้น ถึงแม้ว่าบริษัทจะได้รับแจ้งว่าอาจจะเกิดความเสียหายดังกล่าวขึ้นได้ก็ตาม`, `Unless otherwise specified under the Terms and Conditions of Use, Company, directors, managers, executives, officers, employees, agents, or consultants of the Company shall not be liable for any fault or error of this website, mobile application and social media or information or Contents contained in this website, mobile application and social media and shall assume no responsibility in any omissions relating to this website, mobile application and social media whether in contract, tort, negligence or other consequences which might happen even if advised of the possibility of such damage.`),
            PrivacyPolicy: LanguageUtils.lang(`นโยบายการคุ้มครองข้อมูลส่วนบุคคล`, `Privacy Policy`),
            PrivacyPolicy1: LanguageUtils.lang(`ข้อมูลส่วนบุคคลของท่านสำหรับการใช้งานเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ เช่น ข้อมูลที่ท่านลงทะเบียน ข้อมูลการใช้งานเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของท่าน และ/หรือข้อมูลอื่นใดของท่าน ได้รับความคุ้มครองภายใต้นโยบายความเป็นส่วนตัว (Privacy Policy) โดยท่านสามารถศึกษาข้อมูลเพิ่มเติมได้จาก นโยบายความเป็นส่วนตัว (Privacy Policy) ของบริษัท`, `Your personal information on this website, mobile application and social media, for instance, your registered information, your information of the usage of this website, mobile application and social media and/or other information of you, shall be protected under this Privacy Policy. For more information, `),
            PrivacyPolicyurl: LanguageUtils.lang (`กดที่นี่เพื่อดูรายละเอียด`, `please click here.`),
            Hyperlinks: LanguageUtils.lang(`การเชื่อมโยงเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media)`, `Hyperlinks`),
            Hyperlinks1: LanguageUtils.lang(`การเชื่อมโยงไปยังเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) อื่น : การเชื่อมโยงไปยังเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) อื่น เป็นเพียงการให้บริการเพื่ออำนวยความสะดวกแก่ผู้ใช้บริการเท่านั้น บริษัทมิได้มีส่วนเกี่ยวข้องหรือมีอำนาจควบคุม รับรอง ความถูกต้อง ความน่าเชื่อถือ ตลอดจนความรับผิดชอบในเนื้อหาข้อมูลของเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นั้นๆ และบริษัทไม่รับผิดชอบต่อเนื้อหาใดๆที่แสดงบนเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) อื่นที่เชื่อมโยงมายังเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ของบริษัท หรือต่อความเสียหายใดๆที่เกิดขึ้นจากการเข้าเยี่ยมชมเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ดังกล่าว`, `This website, mobile application and social media contains links to third party sites (“Linked Sites”). Please note that hyperlinks from this website, mobile application and social media to Linked Sites are provided for your convenience only. These Linked Sites are not under the support or control or responsibility of the Company. The Company is not capable of approving for the correctness, reliability or security of the Linked Sites and shall not be liable for any of your loss or damage suffered from using or hyperlinking to such website. Also, you should study terms and conditions of use of the Linked Sites.`),
            Identification: LanguageUtils.lang(`รหัสประจำตัว (Username) และรหัสผ่าน (Password`, `User Identification (User ID) and Password`),
            Identification1: LanguageUtils.lang(`ในการใช้บริการเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) ท่านจะต้องมีรหัสประจำตัว (Username) และรหัสผ่าน (Password) ของตนเอง โดยท่านจะต้องเก็บรักษารหัสประจำตัวและรหัสผ่านของตนเองไว้เป็นความลับ การเข้าใช้งานและทำรายการใด ๆ ที่เกิดขึ้นจากการ Login ผ่านรหัสประจำตัวและรหัสผ่านของท่านในเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ให้ถือว่าการกระทำดังกล่าวถูกต้องสมบูรณ์และเป็นการกระทำของท่านเอง หากมีความเสียหายใด ๆ เกิดขึ้น ไม่ว่าจะด้วยเหตุใดก็ตาม ท่านจะต้องรับผิดชอบในการกระทำดังกล่าวทุกประการ และท่านตกลงจะไม่โต้แย้งหรือเรียกร้องให้บริษัทรับผิดชอบชดใช้ค่าเสียหายแทนท่านทุกกรณี`, `To use this website, mobile application and social media, you shall be required to have your own username (User ID) and password. You shall keep the username and password confidential. Any access or transaction arising from login using your username and password in this website, mobile application and social media shall constitute correct and complete action by you. In case of any damage for whatever reasons, you shall be responsible for all such actions. You further agree that you shall not object or demand Company to be responsible for the damages on your behalf.`),
            Identification2: LanguageUtils.lang(`ท่านสามารถเปลี่ยนแปลง ระงับ หรือยกเลิกรหัสประจำตัวและรหัสผ่าน และ/หรือการใช้บริการเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social Media) นี้ได้ตลอดเวลาด้วยตนเองผ่านช่องทางต่าง ๆ ตามเงื่อนไขและวิธีการที่บริษัทกำหนด ทั้งนี้ บริษัทไม่ต้องรับผิดชอบในความเสียหายใด ๆ ที่เกิดขึ้นก่อนกระบวนการระงับหรือยกเลิกดังกล่าวมีผลสมบูรณ์`, `You may change, suspend or cancel your username and password and/or the usage of this website, mobile application and social media at any time by yourself via any channels in accordance with the conditions and procedures prescribed by the Company. The Company shall assume no responsibility for any damage arising out prior to the effectiveness of the process of such suspending or terminating.`),
            RighttoAccess: LanguageUtils.lang(`สิทธิในการเข้าถึง`, `Right to Access`),
            RighttoAccess1: LanguageUtils.lang(`บริษัทสงวนสิทธิในการปรับปรุงหรือแก้ไขเว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media) หรือเนื้อหาบนเว็บไซต์ mobile
            application และสื่อสังคมออนไลน์ (Social Media) นี้ ในเวลาใดๆ
            รวมทั้งขอสงวนสิทธิที่จะปฏิเสธหรือจำกัดการเข้าถึงเว็บไซต์ mobile
            application และสื่อสังคมออนไลน์ (Social Media) นี้ของบุคคลใด
            หรือจากเลขที่อยู่อินเทอร์เน็ตใด
            โดยไม่จำเป็นต้องบอกกล่าวหรือระบุเหตุผลในการดำเนินการนั้น`, `The Company shall reserve its right to update or modify this website, mobile application and social media or the Contents at any time, including the rights to suspend or limit the access to this website, mobile application and social media of any person or IP address without prior notice or giving reason for such act. `),
            Cookies: LanguageUtils.lang(`Cookies และวิธีการใช้ Cookies`, ` Cookies and how to use Cookies`),
            Cookies1: LanguageUtils.lang(` Cookies คือ text files
            ที่อยู่ในคอมพิวเตอร์ของท่านที่ใช้เพื่อจัดเก็บรายละเอียดข้อมูล log
            การใช้งาน internet ของท่าน หรือ พฤติกรรมการเยี่ยมชม website ของท่าน
            ท่านสามารถศึกษารายละเอียดเพิ่มเติมของ Cookies ได้จาก
            https://www.allaboutcookies.org/`, ` Cookies is text files placed on your computer that are used to store details of your internet usage log information or your website visit behavior. You can learn more about Cookies at https://www.allaboutcookies.org/ `),
            Cookies2: LanguageUtils.lang(`บริษัทจะเก็บรวบรวมข้อมูลบางประการโดยอัตโนมัติจากท่านผ่านการใช้คุกกี้
            บริษัทจะจัดเก็บข้อมูลการเข้าเยี่ยมชมเว็บไซต์จากผู้เข้าเยี่ยมชมทุกรายผ่าน
            Cookies หรือ เทคโนโลยที่ใกล้เคียง และเราจะใช้ Cookies
            เพื่อประโยชน์ในการพัฒนาประสิทธิภาพในการเข้าถึงบริการของบริษัทผ่าน
            internet รวมถึงพัฒนาประสิทธิภาพในการใช้งานบริการของบริษัททาง internet`, ` We will gather certain information automatically from you by using of Cookies. We collect website visit information from all visitors through Cookies or similar technologies and we will use Cookies to improve the efficiency of accessing our services via the internet, including enhancing the efficiency of our use of our service on the internet`),
            Cookies3: LanguageUtils.lang(`ท่านสามารถศึกษาวิธีการตั้งค่าการควบคุมคุกกี้ของท่านผ่านนโยบายการใช้คุกกี้ของเรา`, ` You can learn how to set your cookie controls through our Cookie Policy`),
            cookiesurl: LanguageUtils.lang(`ที่นี่`, `here.`),
            TermsandConditions: LanguageUtils.lang(`การละเมิดข้อตกลงและเงื่อนไขการใช้`, `Violation of Terms and Conditions of Use`),
            TermsandConditions1: LanguageUtils.lang(`ในกรณีมีการละเมิดข้อตกลงและเงื่อนไขการใช้เว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media)
            บริษัทสงวนสิทธิที่จะระงับการเข้าถึงหรือยกเลิกการให้บริการใด ๆ
            ที่มีขึ้นบนเว็บไซต์ mobile application และสื่อสังคมออนไลน์ (Social
            Media) นี้ ทั้งนี้
            การระงับหรือยกเลิกดังกล่าวไม่ถือเป็นการตัดสิทธิบริษัทที่จะได้รับการเยียวยาตามข้อตกลงและเงื่อนไขการใช้นี้
            รวมถึงสิทธิอื่นใดตามกฎหมายที่เกี่ยวข้อง`, `In the event that there is a violation of Terms and Conditions of Use, Company reserves its right to suspend any access to or terminate any services rendered on this website, mobile application and social media without prejudice to Company’s rights to be indemnified under the Terms and Conditions of Use or any other rights under the relevant laws.`),
            Compensation: LanguageUtils.lang(`การชดใช้ค่าเสียหาย`, `Compensation`),
            Compensation1: LanguageUtils.lang(`กรณีที่เกิดความเสียหายแก่บริษัท อันเนื่องมาจากการดำเนินคดี
            การบังคับใช้สิทธิเรียกร้อง
            การชดใช้ค่าเสียหายจากความรับผิดหรือค่าใช้จ่ายใดๆ (รวมถึงค่าทนายความ)
            ที่เกิดขึ้นสืบเนื่องจากการใช้เว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media) ของผู้ใช้บริการ
            ผู้ใช้บริการรับจะชดใช้ความเสียหายดังกล่าวให้แก่บริษัททั้งสิ้น
            ไม่ว่ากรณีดังกล่าวจะเกิดจากการที่ผู้ใช้บริการไม่ปฏิบัติตามเงื่อนไขการให้บริการนี้หรือไม่`, `In the event damages occur to the Company from legal actions, claims or any compensations (including lawyers’ fee) due to the use of this website, mobile application and social media by you. You agree to compensate for such damages incurred whether you have complied with the Terms and Conditions of the Use or not.  `),
            ReservedMatter: LanguageUtils.lang(`ข้อสงวนสิทธิในการดำเนินการเว็บไซต์ mobile application
             และสื่อสังคมออนไลน์ (Social Media)`, `Reserved Matter`),
            ReservedMatter1: LanguageUtils.lang(` บริษัทสงวนสิทธิในการเปลี่ยนแปลงหรือระงับการใช้เว็บไซต์ mobile
            application และสื่อสังคมออนไลน์ (Social Media) ของบริษัทไม่ว่าในเวลาใดๆ
            โดยไม่จำต้องบอกกล่าวแก่ผู้ใช้บริการ
            และโดยปราศจากความรับผิดต่อผู้ใช้บริการหรือต่อบุคคลภายนอก
            กรณีมีความเปลี่ยนแปลงใดๆ บนเว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media)
            ของบริษัทย่อมถือว่าผู้ใช้บริการได้ยอมรับความเปลี่ยนแปลงดังกล่าวแล้ว
            และบริษัทสามารถปฏิเสธสิทธิในการใช้เว็บไซต์ mobile application
            และสื่อสังคมออนไลน์ (Social Media)
            ของบริษัททั้งหมดหรือบางส่วนแก่ผู้ใดก็ได้ โดยไม่ต้องแจ้งล่วงหน้า`, `The Company shall reserve its rights to modify or suspend the use of this website, mobile application and social media at any time without prior notice to the service users and responsibility to the service users. Any change to this website, mobile application and social media shall be deemed that you accept and agree with such change and the Company is entitled to refuse the access to this website, mobile application and social media wholly or partly to any person without prior notice.`),
            GoverningLaws: LanguageUtils.lang(`กฎหมายที่ใช้บังคับ`, `Governing Laws`),
            GoverningLaws1: LanguageUtils.lang(` การตีความ และการบังคับตามเงื่อนไขการให้บริการฉบับนี้
            ให้เป็นไปตามกฎหมายไทย
            หากศาลในบางประเทศจะไม่บังคับใช้กฎหมายประเทศไทยกับข้อพิพาทบางประเภท
            และท่านอาศัยอยู่ในประเทศเหล่านั้น
            ซึ่งกฎหมายของประเทศไทยถูกละเว้นจากการใช้บังคับ
            ก็จะบังคับใช้กฎหมายในประเทศของท่านกับข้อพิพาทที่เกี่ยวข้องกับข้อกำหนดเหล่านี้
            มิฉะนั้น ถือว่าท่านยอมรับว่ากฎหมายของประเทศไทย
            (โดยไม่รวมถึงกฎเกณฑ์การเลือกใช้กฎหมายของประเทศไทย)
            จะมีผลบังคับใช้ต่อข้อพิพาทใดๆ
            ที่เกิดขึ้นจากหรือที่เกี่ยวข้องกับข้อกำหนดเหล่านี้หรือบริการ
            ในลักษณะเดียวกัน
            หากศาลในประเทศของท่านไม่อนุญาตให้ท่านยินยอมให้ใช้อำนาจศาลและสถานที่พิจารณาของศาลในประเทศไทย
            เขตอำนาจศาลและสถานที่พิจารณาในท้องถิ่นของท่านจะถูกใช้บังคับกับข้อพิพาทที่เกี่ยวข้องกับข้อกำหนดเหล่านี้
            มิฉะนั้น
            การเรียกร้องทั้งหมดที่เกิดขึ้นจากหรือเกี่ยวข้องกับข้อกำหนดเหล่านี้หรือบริการจะถูกฟ้องร้องดำเนินคดีเป็นการเฉพาะในศาลประเทศไทย
            และท่านกับบริษัทยินยอมให้ใช้อำนาจศาลตามหลักบุคคลในศาลดังกล่าว`, `Interpretation and enforcement under this Terms and Conditions of Use shall be in accordance with the laws of Thailand. In the event that the court in some countries do not enforce Thai laws to certain type of disputes, in which you have a domicile in that country, the applicable laws under your country shall be applied to the disputes otherwise it shall be deemed that you agree the disputes in relation to the Terms and Conditions of Use and the services or the same type of service (collectively referred to as the “disputes”) shall be governed by the laws of Thailand (not including the rules on application of laws). In the event that the court in your country opposes the jurisdiction and the place of hearing of Thai court, the disputes shall be brought to the jurisdiction and the place of hearing in which your domicile is situated, otherwise all claims incurred from or in relation to the Terms and Conditions of Use or the services shall be brought to Thai court and it shall be deemed that you and the Company agrees to be governed by the rules of personal jurisdiction under Thai court. `),
            ContactUs : LanguageUtils.lang(`รายละเอียดการติดต่อเรา`, `Contact Us`),
            ContactUs1 : LanguageUtils.lang(`หากท่านมีข้อสงสัยเกี่ยวกับข้อตกลงและเงื่อนไขฉบับนี้ โปรดติดต่อเราที่`, `If you have any questions about this Terms and Conditions of Use, please contact us at:`),
            ContactUs2 : LanguageUtils.lang(`บริษัท เซ็นทรัลพัฒนา จำกัด (มหาชน)`, `Central Pattana Public Company Limited `),
            ContactUs3 : LanguageUtils.lang(` อาคารดิออฟฟิศเศส แอท เซ็นทรัลเวิลด์ 999/9 ถนนพระราม 1 แขวงปทุมวัน
            เขตปทุมวัน กรุงเทพมหานคร 10330 ประเทศไทย`, `The Offices at Central World, 999/9 Rama 1 Rd., Pathumwan, Bangkok 10330, Thailand`),
            ContactUs4 : LanguageUtils.lang(`+66 (0) 2-667-5555`, `+66 (0) 2-667-5555`),
           

        };
    }
}
export {
    TermAndCondition
}
